WIP: break out e2e snapshots

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -67,6 +67,160 @@ jobs:
           set -euo pipefail
           echo "significant: ${{ steps.path-changes.outputs.significant }}"
           echo "should-run: ${{ steps.should-run.outputs.should-run }}"
+  
+  snapshots:
+    name: playwright:snapshots:ubuntu
+    runs-on: namespace-profile-ubuntu-8-cores
+    needs: conditions
+    steps:
+    - uses: actions/create-github-app-token@v1
+      id: app-token
+      with:
+        app-id: ${{ secrets.MODELING_APP_GH_APP_ID }}
+        private-key: ${{ secrets.MODELING_APP_GH_APP_PRIVATE_KEY }}
+        owner: ${{ github.repository_owner }}
+    - id: filter
+      name: Check for Rust changes
+      uses: dorny/paths-filter@v3
+      with:
+        filters: |
+          rust:
+            - 'rust/**'
+    - uses: actions/setup-node@v4
+      if: needs.conditions.outputs.should-run == 'true'
+      with:
+        node-version-file: '.nvmrc'
+        cache: 'yarn'
+    - name: Install dependencies
+      id: deps-install
+      if: needs.conditions.outputs.should-run == 'true'
+      shell: bash
+      run: yarn
+    - name: Cache Playwright Browsers
+      if: needs.conditions.outputs.should-run == 'true'
+      uses: actions/cache@v4
+      with:
+        path: |
+          ~/.cache/ms-playwright/
+        key: ${{ runner.os }}-playwright-${{ hashFiles('yarn.lock') }}
+    - name: Install Playwright Browsers
+      if: needs.conditions.outputs.should-run == 'true'
+      shell: bash
+      run: yarn playwright install --with-deps
+    - name: Download Wasm Cache
+      id: download-wasm
+      if: ${{ needs.conditions.outputs.should-run == 'true' && github.event_name != 'schedule' && steps.filter.outputs.rust == 'false' }}
+      uses: dawidd6/action-download-artifact@v7
+      continue-on-error: true
+      with:
+        github_token: ${{secrets.GITHUB_TOKEN}}
+        name: wasm-bundle
+        workflow: build-and-store-wasm.yml
+        branch: main
+        path: rust/kcl-wasm-lib/pkg
+    - name: copy wasm blob
+      if: ${{ needs.conditions.outputs.should-run == 'true' && github.event_name != 'schedule' && steps.filter.outputs.rust == 'false' }}
+      shell: bash
+      run: cp rust/kcl-wasm-lib/pkg/kcl_wasm_lib_bg.wasm public
+      continue-on-error: true
+    - name: Build WASM condition
+      id: wasm
+      if: needs.conditions.outputs.should-run == 'true'
+      shell: bash
+      run: |
+        set -euox pipefail
+        # Build wasm if this is a scheduled run, there are Rust changes, or
+        # downloading from the wasm cache failed.
+        if [[ ${{github.event_name}} == 'schedule' || ${{steps.filter.outputs.rust}} == 'true' || ${{steps.download-wasm.outcome}} == 'failure' ]]; then
+          echo "should-build-wasm=true" >> $GITHUB_OUTPUT
+        else
+          echo "should-build-wasm=false" >> $GITHUB_OUTPUT
+        fi
+    - name: Use correct Rust toolchain
+      if: ${{ needs.conditions.outputs.should-run == 'true' && steps.wasm.outputs.should-build-wasm == 'true' }}
+      shell: bash
+      run: |
+        [ -e rust-toolchain.toml ] || cp rust/rust-toolchain.toml ./
+    - name: Install rust
+      if: ${{ needs.conditions.outputs.should-run == 'true' && steps.wasm.outputs.should-build-wasm == 'true' }}
+      uses: actions-rust-lang/setup-rust-toolchain@v1
+      with:
+        cache: false # Configured below.
+    - uses: taiki-e/install-action@955a6ff1416eae278c9f833008a9beb4b7f9afe3
+      if: ${{ needs.conditions.outputs.should-run == 'true' && steps.wasm.outputs.should-build-wasm == 'true' }}
+      with:
+        tool: wasm-pack
+    - name: Rust Cache
+      if: ${{ needs.conditions.outputs.should-run == 'true' && steps.wasm.outputs.should-build-wasm == 'true' }}
+      uses: Swatinem/rust-cache@v2
+      with:
+        workspaces: './rust'
+    - name: Build Wasm
+      if: ${{ needs.conditions.outputs.should-run == 'true' && steps.wasm.outputs.should-build-wasm == 'true' }}
+      shell: bash
+      run: yarn build:wasm
+    - name: build web
+      if: needs.conditions.outputs.should-run == 'true'
+      shell: bash
+      run: yarn tronb:vite:dev
+    - name: Run ubuntu/chrome snapshots
+      if: ${{ needs.conditions.outputs.should-run == 'true' && matrix.os == 'namespace-profile-ubuntu-8-cores' && matrix.shardIndex == 1 }}
+      shell: bash
+      # TODO: break this in its own job, for now it's not slowing down the overall execution as ubuntu is the quickest,
+      # but we could do better. This forces a large 1/1 shard of all 20 snapshot tests that runs in about 3 minutes.
+      run: |
+        yarn test:snapshots
+      env:
+        CI: true
+        NODE_ENV: development
+        VITE_KC_DEV_TOKEN: ${{ secrets.KITTYCAD_API_TOKEN_DEV }}
+        VITE_KC_SKIP_AUTH: true
+        token: ${{ secrets.KITTYCAD_API_TOKEN_DEV }}
+        snapshottoken: ${{ secrets.KITTYCAD_API_TOKEN }}
+    - uses: actions/upload-artifact@v4
+      if: ${{ needs.conditions.outputs.should-run == 'true' && !cancelled() && (success() || failure()) }}
+      with:
+        name: playwright-report-snapshots-${{ matrix.os }}-snapshot-${{ matrix.shardIndex }}-${{ github.sha }}
+        path: playwright-report/
+        include-hidden-files: true
+        retention-days: 30
+        overwrite: true
+    - name: Clean up test-results
+      if: ${{ needs.conditions.outputs.should-run == 'true' && !cancelled() && (success() || failure()) }}
+      continue-on-error: true
+      run: rm -r test-results
+    - name: check for changes
+      if: ${{ needs.conditions.outputs.should-run == 'true' && matrix.os == 'namespace-profile-ubuntu-8-cores' && matrix.shardIndex == 1 && github.ref != 'refs/heads/main' }}
+      shell: bash
+      id: git-check
+      run: |
+          git add e2e/playwright/snapshot-tests.spec.ts-snapshots e2e/playwright/snapshots
+          if git status | grep -q "Changes to be committed"
+          then echo "modified=true" >> $GITHUB_OUTPUT
+          else echo "modified=false" >> $GITHUB_OUTPUT
+          fi
+    - name: Commit changes, if any
+      if: ${{ needs.conditions.outputs.should-run == 'true' && steps.git-check.outputs.modified == 'true' }}
+      shell: bash
+      run: |
+        git add e2e/playwright/snapshot-tests.spec.ts-snapshots e2e/playwright/snapshots
+        git config --local user.email "github-actions[bot]@users.noreply.github.com"
+        git config --local user.name "github-actions[bot]"
+        git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
+        git fetch origin
+        echo ${{ github.head_ref }}
+        git checkout ${{ github.head_ref }}
+        git commit -m "A snapshot a day keeps the bugs away! 📷🐛 (OS: ${{matrix.os}})" || true
+        git push
+        git push origin ${{ github.head_ref }}
+    # only upload artifacts if there's actually changes
+    - uses: actions/upload-artifact@v4
+      if: ${{ needs.conditions.outputs.should-run == 'true' && steps.git-check.outputs.modified == 'true' }}
+      with:
+        name: playwright-report-${{ matrix.os }}-${{ matrix.shardIndex }}-${{ github.sha }}
+        path: playwright-report/
+        include-hidden-files: true
+        retention-days: 30
 
   electron:
     timeout-minutes: 60
@@ -82,15 +236,7 @@ jobs:
     runs-on: ${{ matrix.os }}
     needs: conditions
     steps:
-    - uses: actions/create-github-app-token@v1
-      id: app-token
-      with:
-        app-id: ${{ secrets.MODELING_APP_GH_APP_ID }}
-        private-key: ${{ secrets.MODELING_APP_GH_APP_PRIVATE_KEY }}
-        owner: ${{ github.repository_owner }}
     - uses: actions/checkout@v4
-      with:
-        token: ${{ steps.app-token.outputs.token }}
     - id: filter
       name: Check for Rust changes
       uses: dorny/paths-filter@v3
@@ -198,64 +344,6 @@ jobs:
       if: needs.conditions.outputs.should-run == 'true'
       shell: bash
       run: yarn tronb:vite:dev
-    - name: Run ubuntu/chrome snapshots
-      if: ${{ needs.conditions.outputs.should-run == 'true' && matrix.os == 'namespace-profile-ubuntu-8-cores' && matrix.shardIndex == 1 }}
-      shell: bash
-      # TODO: break this in its own job, for now it's not slowing down the overall execution as ubuntu is the quickest,
-      # but we could do better. This forces a large 1/1 shard of all 20 snapshot tests that runs in about 3 minutes.
-      run: |
-        yarn test:snapshots
-      env:
-        CI: true
-        NODE_ENV: development
-        VITE_KC_DEV_TOKEN: ${{ secrets.KITTYCAD_API_TOKEN_DEV }}
-        VITE_KC_SKIP_AUTH: true
-        token: ${{ secrets.KITTYCAD_API_TOKEN_DEV }}
-        snapshottoken: ${{ secrets.KITTYCAD_API_TOKEN }}
-    - uses: actions/upload-artifact@v4
-      if: ${{ needs.conditions.outputs.should-run == 'true' && !cancelled() && (success() || failure()) }}
-      with:
-        name: playwright-report-snapshots-${{ matrix.os }}-snapshot-${{ matrix.shardIndex }}-${{ github.sha }}
-        path: playwright-report/
-        include-hidden-files: true
-        retention-days: 30
-        overwrite: true
-    - name: Clean up test-results
-      if: ${{ needs.conditions.outputs.should-run == 'true' && !cancelled() && (success() || failure()) }}
-      continue-on-error: true
-      run: rm -r test-results
-    - name: check for changes
-      if: ${{ needs.conditions.outputs.should-run == 'true' && matrix.os == 'namespace-profile-ubuntu-8-cores' && matrix.shardIndex == 1 && github.ref != 'refs/heads/main' }}
-      shell: bash
-      id: git-check
-      run: |
-          git add e2e/playwright/snapshot-tests.spec.ts-snapshots e2e/playwright/snapshots
-          if git status | grep -q "Changes to be committed"
-          then echo "modified=true" >> $GITHUB_OUTPUT
-          else echo "modified=false" >> $GITHUB_OUTPUT
-          fi
-    - name: Commit changes, if any
-      if: ${{ needs.conditions.outputs.should-run == 'true' && steps.git-check.outputs.modified == 'true' }}
-      shell: bash
-      run: |
-        git add e2e/playwright/snapshot-tests.spec.ts-snapshots e2e/playwright/snapshots
-        git config --local user.email "github-actions[bot]@users.noreply.github.com"
-        git config --local user.name "github-actions[bot]"
-        git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
-        git fetch origin
-        echo ${{ github.head_ref }}
-        git checkout ${{ github.head_ref }}
-        git commit -m "A snapshot a day keeps the bugs away! 📷🐛 (OS: ${{matrix.os}})" || true
-        git push
-        git push origin ${{ github.head_ref }}
-    # only upload artifacts if there's actually changes
-    - uses: actions/upload-artifact@v4
-      if: ${{ needs.conditions.outputs.should-run == 'true' && steps.git-check.outputs.modified == 'true' }}
-      with:
-        name: playwright-report-${{ matrix.os }}-${{ matrix.shardIndex }}-${{ github.sha }}
-        path: playwright-report/
-        include-hidden-files: true
-        retention-days: 30
     - uses: actions/download-artifact@v4
       if: ${{ needs.conditions.outputs.should-run == 'true' && !cancelled() && (success() || failure()) }}
       continue-on-error: true
@@ -294,4 +382,3 @@ jobs:
         include-hidden-files: true
         retention-days: 30
         overwrite: true
-
