temporarily disable snapshots step

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -105,54 +105,54 @@ jobs:
       run: yarn build:wasm
     - name: build web
       run: yarn build:local
-    - name: Run ubuntu/chrome snapshots
-      continue-on-error: true
-      run: |
-        yarn playwright test --project="Google Chrome" --update-snapshots e2e/playwright/snapshot-tests.spec.ts
-      env:
-        CI: true
-        token: ${{ secrets.KITTYCAD_API_TOKEN_DEV }}
-        snapshottoken: ${{ secrets.KITTYCAD_API_TOKEN }}
-    - name: Clean up test-results
-      if: always()
-      continue-on-error: true
-      run: rm -r test-results
-    - name: check for changes
-      id: git-check
-      run: |
-          git add .
-          if git status | grep -q "Changes to be committed"
-          then echo "modified=true" >> $GITHUB_OUTPUT
-          else echo "modified=false" >> $GITHUB_OUTPUT
-          fi
-    - name: Commit changes, if any
-      if: steps.git-check.outputs.modified == 'true'
-      run: |
-        git add .
-        git config --local user.email "github-actions[bot]@users.noreply.github.com"
-        git config --local user.name "github-actions[bot]"
-        git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
-        git fetch origin
-        echo ${{ github.head_ref }}
-        git checkout ${{ github.head_ref }}
-        # TODO when webkit works on ubuntu remove the os part of the commit message
-        git commit -am "A snapshot a day keeps the bugs away! 📷🐛 (OS: ubuntu)" || true
-        git push
-        git push origin ${{ github.head_ref }}
-    # only upload artifacts if there's actually changes
-    - uses: actions/upload-artifact@v4
-      if: steps.git-check.outputs.modified == 'true'
-      with:
-        name: playwright-report-ubuntu-${{ github.sha }}
-        path: playwright-report/
-        retention-days: 30
-    # if have previous run results, use them
-    - uses: actions/download-artifact@v4
-      if: always()
-      continue-on-error: true
-      with:
-        name: test-results-ubuntu-${{ github.sha }}
-        path: test-results/
+    # - name: Run ubuntu/chrome snapshots
+    #   continue-on-error: true
+    #   run: |
+    #     yarn playwright test --project="Google Chrome" --update-snapshots e2e/playwright/snapshot-tests.spec.ts
+    #   env:
+    #     CI: true
+    #     token: ${{ secrets.KITTYCAD_API_TOKEN_DEV }}
+    #     snapshottoken: ${{ secrets.KITTYCAD_API_TOKEN }}
+    # - name: Clean up test-results
+    #   if: always()
+    #   continue-on-error: true
+    #   run: rm -r test-results
+    # - name: check for changes
+    #   id: git-check
+    #   run: |
+    #       git add .
+    #       if git status | grep -q "Changes to be committed"
+    #       then echo "modified=true" >> $GITHUB_OUTPUT
+    #       else echo "modified=false" >> $GITHUB_OUTPUT
+    #       fi
+    # - name: Commit changes, if any
+    #   if: steps.git-check.outputs.modified == 'true'
+    #   run: |
+    #     git add .
+    #     git config --local user.email "github-actions[bot]@users.noreply.github.com"
+    #     git config --local user.name "github-actions[bot]"
+    #     git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
+    #     git fetch origin
+    #     echo ${{ github.head_ref }}
+    #     git checkout ${{ github.head_ref }}
+    #     # TODO when webkit works on ubuntu remove the os part of the commit message
+    #     git commit -am "A snapshot a day keeps the bugs away! 📷🐛 (OS: ubuntu)" || true
+    #     git push
+    #     git push origin ${{ github.head_ref }}
+    # # only upload artifacts if there's actually changes
+    # - uses: actions/upload-artifact@v4
+    #   if: steps.git-check.outputs.modified == 'true'
+    #   with:
+    #     name: playwright-report-ubuntu-${{ github.sha }}
+    #     path: playwright-report/
+    #     retention-days: 30
+    # # if have previous run results, use them
+    # - uses: actions/download-artifact@v4
+    #   if: always()
+    #   continue-on-error: true
+    #   with:
+    #     name: test-results-ubuntu-${{ github.sha }}
+    #     path: test-results/
     - name: Run ubuntu/chrome flow (with retries)
       id: retry
       if: always()
